services:
  - type: web
    name: flarum-forum
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: FORUM_URL
        value: https://your-flarum.onrender.com       # 替换为你的域名
      - key: DB_HOST
        value: your-db.supabase.co                    # Supabase 或外部数据库地址
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_password
      - key: DB_DRIVER
        value: pgsql